apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model-api
  labels:
    app: ai-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-model
  template:
    metadata:
      labels:
        app: ai-model
    spec:
      volumes:
        - name: model-volume
          emptyDir: {}

      initContainers:
        - name: download-model
          image: python:3.12-slim
          command:
            - sh
            - -c
            - |
              pip install --no-cache-dir gdown && \
              gdown "https://drive.google.com/uc?id=YOUR_FILE_ID" -O /model/model.zip && \
              unzip /model/model.zip -d /model && \
              rm /model/model.zip
          volumeMounts:
            - name: model-volume
              mountPath: /model

      containers:
        - name: api
          image: omarhussein2111/ai-model-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          volumeMounts:
            - name: model-volume
              mountPath: /app/model

          env:
            - name: MODEL_DIR
              value: /app/model

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: ai-model-service
spec:
  type: NodePort
  selector:
    app: ai-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30006